# Generated by Django 3.0.5 on 2023-04-28 21:44

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_data', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='', max_length=150)),
                ('last_name', models.CharField(default='', max_length=150)),
                ('address', models.CharField(default='', max_length=200)),
                ('phone', models.CharField(default='', max_length=20)),
                ('age', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('sex', models.CharField(choices=[('m', 'Male'), ('f', 'Female'), ('o', 'Other')], default='', max_length=1)),
                ('email', models.EmailField(default='', max_length=254)),
                ('image', models.FileField(default='', upload_to='images/')),
                ('designation', models.CharField(max_length=150)),
                ('degree', models.CharField(max_length=150)),
                ('experience', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('professional_statement_text', models.TextField()),
                ('education', models.TextField()),
                ('payment_statement', models.TextField()),
                ('start_duty_day', models.CharField(choices=[('Mon', 'Monday'), ('Tues', 'Tuesday'), ('Wed', 'Wednesday'), ('Thurs', 'Thursday'), ('Fri', 'Friday'), ('Sat', 'Saturday'), ('Sun', 'Sunday')], max_length=9)),
                ('end_duty_day', models.CharField(choices=[('Mon', 'Monday'), ('Tues', 'Tuesday'), ('Wed', 'Wednesday'), ('Thurs', 'Thursday'), ('Fri', 'Friday'), ('Sat', 'Saturday'), ('Sun', 'Sunday')], max_length=9)),
                ('start_time', models.TimeField(verbose_name='start time')),
                ('end_time', models.TimeField(verbose_name='end time')),
            ],
        ),
        migrations.CreateModel(
            name='LabDoc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='', max_length=150)),
                ('last_name', models.CharField(default='', max_length=150)),
                ('address', models.CharField(default='', max_length=200)),
                ('phone', models.CharField(default='', max_length=20)),
                ('age', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('sex', models.CharField(choices=[('m', 'Male'), ('f', 'Female'), ('o', 'Other')], default='', max_length=1)),
                ('email', models.EmailField(default='', max_length=254)),
                ('image', models.FileField(default='', upload_to='images/')),
                ('designation', models.CharField(max_length=150)),
                ('degree', models.CharField(max_length=150)),
                ('experience', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
            ],
        ),
        migrations.CreateModel(
            name='Nurse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='', max_length=150)),
                ('last_name', models.CharField(default='', max_length=150)),
                ('address', models.CharField(default='', max_length=200)),
                ('phone', models.CharField(default='', max_length=20)),
                ('age', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('sex', models.CharField(choices=[('m', 'Male'), ('f', 'Female'), ('o', 'Other')], default='', max_length=1)),
                ('email', models.EmailField(default='', max_length=254)),
                ('image', models.FileField(default='', upload_to='images/')),
                ('designation', models.CharField(max_length=150)),
                ('degree', models.CharField(max_length=150)),
                ('experience', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
            ],
        ),
        migrations.CreateModel(
            name='Receptionist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='', max_length=150)),
                ('last_name', models.CharField(default='', max_length=150)),
                ('address', models.CharField(default='', max_length=200)),
                ('phone', models.CharField(default='', max_length=20)),
                ('age', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('sex', models.CharField(choices=[('m', 'Male'), ('f', 'Female'), ('o', 'Other')], default='', max_length=1)),
                ('email', models.EmailField(default='', max_length=254)),
                ('image', models.FileField(default='', upload_to='images/')),
                ('degree', models.CharField(max_length=150)),
                ('experience', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_title', models.CharField(max_length=50)),
                ('service_summary', models.CharField(max_length=150)),
                ('text', models.TextField()),
                ('image', models.FileField(default='', upload_to='images/')),
                ('icon', models.FileField(default='', upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Specialization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialization', models.CharField(max_length=200)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specialization', to='pages.Doctor')),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_name', models.CharField(max_length=30)),
                ('date', models.DateField(verbose_name='date of report generation')),
                ('result_summary', models.CharField(max_length=200)),
                ('investigations', models.TextField()),
                ('test_price', models.DecimalField(decimal_places=2, max_digits=20, validators=[django.core.validators.MinValueValidator(0)])),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pages.Doctor')),
                ('lab_doctor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pages.LabDoc')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disease_name', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=20, validators=[django.core.validators.MinValueValidator(0)])),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price', to='pages.Doctor')),
            ],
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='', max_length=150)),
                ('last_name', models.CharField(default='', max_length=150)),
                ('address', models.CharField(default='', max_length=200)),
                ('phone', models.CharField(default='', max_length=20)),
                ('age', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('sex', models.CharField(choices=[('m', 'Male'), ('f', 'Female'), ('o', 'Other')], default='', max_length=1)),
                ('email', models.EmailField(default='', max_length=254)),
                ('image', models.FileField(default='', upload_to='images/')),
                ('occupation', models.CharField(blank=True, max_length=100, null=True)),
                ('presenting_complaint', models.TextField(blank=True, null=True)),
                ('presenting_complaint_detail', models.TextField(blank=True, null=True)),
                ('past_medical_history', models.TextField(blank=True, null=True)),
                ('past_surgical_history', models.TextField(blank=True, null=True)),
                ('past_drug_history', models.TextField(blank=True, null=True)),
                ('drug_allergy', models.TextField(blank=True, null=True)),
                ('vaccination_history', models.TextField(blank=True, null=True)),
                ('personal_history', models.TextField(blank=True, null=True)),
                ('economic_status', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Curriculum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('major_subject', models.CharField(max_length=200)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curriculum', to='pages.Doctor')),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='date selected')),
                ('time', models.TimeField(verbose_name='time selected')),
                ('doctor', models.IntegerField(default=0)),
                ('disease_option', models.CharField(default='', max_length=50)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
